import { writeFileSync, mkdirSync } from 'node:fs';
import { dirname } from 'node:path';
import type { TrainingRun, CourseMeta, Scenario } from '../types/index.js';

/**
 * Generate a detailed markdown report of a training run.
 * Designed as a showcase document showing the full dojo.md pipeline.
 */
export function generateReport(
  course: CourseMeta,
  scenarios: Scenario[],
  run: TrainingRun,
  skillContent: string | null,
  outputPath: string,
): void {
  const lines: string[] = [];
  const scenarioMap = new Map(scenarios.map((s) => [s.meta.id, s]));

  // ─── Header ────────────────────────────────────────────────
  lines.push(`# Training Report: ${course.name}`);
  lines.push('');
  lines.push(`> Generated by dojo.md | ${new Date().toISOString().split('T')[0]}`);
  lines.push('');

  // ─── Stage 1: Course Overview ──────────────────────────────
  lines.push('## Stage 1 — Course Loaded');
  lines.push('');
  lines.push(`| Field | Value |`);
  lines.push(`|-------|-------|`);
  lines.push(`| **Course** | ${course.name} |`);
  lines.push(`| **ID** | \`${course.id}\` |`);
  lines.push(`| **Levels** | ${course.levels} |`);
  lines.push(`| **Scenarios** | ${scenarios.length} |`);
  lines.push(`| **Tags** | ${course.tags.join(', ')} |`);
  lines.push('');
  lines.push(`*${course.description.trim()}*`);
  lines.push('');
  lines.push('---');
  lines.push('');

  // ─── Stage 2: Scenario Results ─────────────────────────────
  lines.push('## Stage 2 — Training Run');
  lines.push('');

  const scoreColor = run.score >= 80 ? '🟢' : run.score >= 50 ? '🟡' : '🔴';
  lines.push(`**Overall Score: ${scoreColor} ${run.score}/100**`);
  lines.push('');

  for (const levelResult of run.levelResults) {
    lines.push(`### Level ${levelResult.level} — ${levelResult.passed}/${levelResult.total} passed`);
    lines.push('');

    for (const result of levelResult.scenarioResults) {
      const scenario = scenarioMap.get(result.scenarioId);
      const icon = result.passed ? '✅' : '❌';

      lines.push(`#### ${icon} \`${result.scenarioId}\``);
      lines.push('');

      if (scenario) {
        lines.push(`**Description:** ${scenario.meta.description}`);
        lines.push('');
        lines.push('<details>');
        lines.push('<summary>Trigger (click to expand)</summary>');
        lines.push('');
        lines.push('```');
        lines.push(scenario.trigger.trim());
        lines.push('```');
        lines.push('</details>');
        lines.push('');
      }

      // Agent response (truncated)
      if (result.agentResponse) {
        const truncated = result.agentResponse.length > 500
          ? result.agentResponse.slice(0, 500) + '\n\n*[truncated — ' + result.agentResponse.length + ' chars total]*'
          : result.agentResponse;

        lines.push('<details>');
        lines.push('<summary>Agent Response (click to expand)</summary>');
        lines.push('');
        lines.push(truncated);
        lines.push('');
        lines.push('</details>');
        lines.push('');
      }

      // Assertion results
      if (result.assertions.length > 0) {
        lines.push('**Assertions:**');
        lines.push('');
        lines.push('| # | Description | Type | Weight | Score | Result |');
        lines.push('|---|-------------|------|--------|-------|--------|');

        for (let i = 0; i < result.assertions.length; i++) {
          const a = result.assertions[i];
          const weight = a.assertion.weight !== undefined ? a.assertion.weight.toFixed(1) : '—';
          const score = a.score !== undefined ? `${a.score}/100` : (a.passed ? '100' : '0');
          const icon = a.passed ? '✅' : '❌';
          lines.push(`| ${i + 1} | ${a.assertion.description} | \`${a.assertion.type}\` | ${weight} | ${score} | ${icon} |`);
        }
        lines.push('');

        // Show reasoning for failed assertions
        const failed = result.assertions.filter((a) => !a.passed);
        if (failed.length > 0) {
          lines.push('<details>');
          lines.push('<summary>Failure reasoning</summary>');
          lines.push('');
          for (const a of failed) {
            lines.push(`- **${a.assertion.description}**: ${a.reasoning || 'No reasoning provided'}`);
          }
          lines.push('');
          lines.push('</details>');
          lines.push('');
        }
      }

      lines.push('---');
      lines.push('');
    }
  }

  // ─── Stage 3: Failure Patterns ─────────────────────────────
  lines.push('## Stage 3 — Failure Pattern Extraction');
  lines.push('');

  if (run.failurePatterns.length === 0) {
    lines.push('*No failure patterns — clean run!*');
  } else {
    lines.push(`**${run.failurePatterns.length} failure pattern(s) extracted:**`);
    lines.push('');
    lines.push('| # | Severity | Category | Frequency | Description |');
    lines.push('|---|----------|----------|-----------|-------------|');

    for (let i = 0; i < run.failurePatterns.length; i++) {
      const p = run.failurePatterns[i];
      const severityIcon = { critical: '🔴', high: '🟠', medium: '🟡', low: '🟢' }[p.severity] || '⚪';
      lines.push(`| ${i + 1} | ${severityIcon} ${p.severity} | \`${p.category}\` | ${p.frequency}x | ${p.description} |`);
    }
    lines.push('');

    lines.push('### Suggested Fixes');
    lines.push('');
    for (let i = 0; i < run.failurePatterns.length; i++) {
      const p = run.failurePatterns[i];
      lines.push(`${i + 1}. **${p.description}**`);
      lines.push(`   - Fix: ${p.suggestedFix}`);
      lines.push(`   - Affected: ${p.scenarioIds.join(', ')}`);
      lines.push('');
    }
  }

  lines.push('---');
  lines.push('');

  // ─── Stage 4: Generated SKILL.md ───────────────────────────
  lines.push('## Stage 4 — Generated SKILL.md');
  lines.push('');

  if (skillContent) {
    lines.push('The following SKILL.md was generated from the failure patterns:');
    lines.push('');
    lines.push('```markdown');
    lines.push(skillContent.trim());
    lines.push('```');
  } else {
    lines.push('*No SKILL.md generated (no failure patterns).*');
  }

  lines.push('');
  lines.push('---');
  lines.push('');
  lines.push(`*Report generated by dojo.md v${course.version || '0.1.0'}*`);

  mkdirSync(dirname(outputPath), { recursive: true });
  writeFileSync(outputPath, lines.join('\n'), 'utf-8');
}
